export const OPENMESSAGE = 'OPENMESSAGE'
export const CLOSEMESSAGE = 'CLOSEMESSAGE'
export const SENDMESSAGE = 'SENDMESSAGE'
export const SELECTED = 'SELECTED'
export const USER = 'USER'
export const setTotal = 'setTotal'
export const addtocart='addtocart'
export const removefromcart='removefromcart'